// Fish writer: native fish syntax, not bash exports wrapped in `bass`.
// fish has no `export` and rejects POSIX `$(...)` command substitution -
// its forms are `set -gx VAR value` and `(command)`. Registry metadata
// values are written as POSIX shell expressions (the zsh/bash writer
// embeds them verbatim), so this writer translates the two constructs
// fish handles differently:
//   $(command)  ->  (command)     (fish command substitution)
//   $HOME/$VAR  ->  unchanged     (fish variable syntax is identical)
// A value using POSIX-only syntax beyond that (backticks, ${VAR%...}
// parameter expansion) can't be translated mechanically - it's emitted
// as a commented-out line with an explanation, never silently dropped
// and never emitted broken.
const UNTRANSLATABLE = /`|\$\{[^}]*[#%^,:][^}]*\}/;

export function translatePosixToFish(expression) {
    if (UNTRANSLATABLE.test(expression)) return null;
    return expression.replace(/\$\(/g, "(");
}

function emit(lines, expression, render) {
    const translated = translatePosixToFish(expression);
    if (translated === null) {
        lines.push(`# skipped (POSIX-only syntax, no fish equivalent generated): ${expression}`);
        return;
    }
    render(translated);
}

export function renderFishShellFile(model) {
    const lines = [
        "# Generated by DevForgeKit's Environment Configuration Engine.",
        "# Do not edit by hand - regenerated on every package install and",
        "# 'devforgekit env regenerate'. Run 'devforgekit env doctor' to inspect.",
        "# Shell: fish",
        ""
    ];

    if (model.path.length > 0) {
        for (const entry of model.path) {
            emit(lines, entry, (translated) => {
                lines.push(`set -gx PATH ${translated} $PATH`);
            });
        }
        lines.push("");
    }

    const variableEntries = Object.entries(model.variables);
    if (variableEntries.length > 0) {
        for (const [key, def] of variableEntries) {
            const expression = def.command ? `(${def.command})` : def.value;
            emit(lines, expression, (translated) => {
                lines.push(`set -gx ${key} ${def.command ? translated : `"${translated}"`}`);
            });
        }
        lines.push("");
    }

    if (model.shell.length > 0) {
        for (const { packageName, line } of model.shell) {
            // Raw shell lines are POSIX-authored (e.g. `eval "$(mise
            // activate zsh)"`) and usually have a fish-specific
            // counterpart the manifest hasn't declared - emitting the
            // POSIX form into fish would break at startup, so it's
            // commented out with attribution instead.
            lines.push(`# ${packageName}: declared shell line is POSIX syntax - add a fish variant to the manifest to enable it here`, `# ${line}`);
        }
        lines.push("");
    }

    return `${lines.join("\n").trimEnd()}\n`;
}
