// Shared renderer for zsh and bash - both consume identical POSIX
// export/PATH syntax (workspace/shellIntegration.js's buildShellLines
// already relies on this same fact for its per-workspace exports).
//
// Values come directly from trusted, registry-authored YAML, never from
// installed-package free-text output or user input - so they're
// embedded inside double quotes to let $HOME/$VARNAME expansion and
// $(command) substitution actually happen, deliberately NOT run through
// a shell-escaping helper like core/shell.js's shellQuote() (which
// single-quotes a value specifically to PREVENT expansion - correct for
// workspace secrets, wrong here, where expansion is the entire point of
// "$HOME/development/flutter/bin" or "$(brew --prefix openjdk)").
export function renderPosixShellFile(model, { shellName }) {
    const lines = [
        "# Generated by DevForgeKit's Environment Configuration Engine.",
        "# Do not edit by hand - regenerated on every package install and",
        "# 'devforgekit env regenerate'. Run 'devforgekit env doctor' to inspect.",
        `# Shell: ${shellName}`,
        ""
    ];

    if (model.path.length > 0) {
        lines.push(`export PATH="${model.path.join(":")}:$PATH"`, "");
    }

    const variableEntries = Object.entries(model.variables);
    if (variableEntries.length > 0) {
        for (const [key, def] of variableEntries) {
            lines.push(def.command ? `export ${key}="$(${def.command})"` : `export ${key}="${def.value}"`);
        }
        lines.push("");
    }

    if (model.shell.length > 0) {
        for (const { packageName, line } of model.shell) {
            lines.push(`# ${packageName}`, line);
        }
        lines.push("");
    }

    return `${lines.join("\n").trimEnd()}\n`;
}
