// Built-in theme definitions for the DevForgeKit TUI theme system.
// Each theme defines all 28 semantic color tokens (see theme.js's
// THEME_TOKENS list). Colors are Ink <Text color=...> values: named ANSI
// colors or hex strings. Named colors degrade gracefully on 16-color
// terminals; hex gives precise control on true-color emulators.
//
// Every theme also carries metadata (name, author, version, description,
// homepage, license) for future sharing/marketplace support.
//
// The `dark` theme is the default (v1.4.0 redesign - see docs/TUI.md's
// "Default theme redesign" section): a real hex palette instead of
// undefined/named-ANSI placeholders, bringing it in line with every
// other built-in theme below (which already ship full backgrounds,
// selection colors, etc.) - and fixing the one real contrast bug the
// old palette had, `selection: "cyan"` paired with `selectionText:
// "black"`, which read as washed-out on true-color terminals instead
// of the crisp white-on-solid-blue every other theme uses for its
// selected state.

export const BUILTIN_THEMES = [
    {
        id: "dark",
        name: "DevForgeKit Dark",
        author: "DevForgeKit",
        version: "2.0.0",
        description: "Default dark theme - high-contrast, GitHub Dark-inspired premium palette",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#161B22",
            surface: "#1E2430",
            surfaceAlt: "#232A36",
            text: "#F8FAFC",
            textMuted: "#C9D1D9",
            textDisabled: "#6E7681",
            primary: "#58A6FF",
            secondary: "#BC8CFF",
            accent: "#58A6FF",
            panelTitle: "#56D4DD",
            success: "#3FB950",
            warning: "#D29922",
            error: "#F85149",
            info: "#79C0FF",
            border: "#3B4658",
            borderActive: "#58A6FF",
            selection: "#1F6FEB",
            selectionText: "#FFFFFF",
            header: "#0D1117",
            footer: "#0D1117",
            sidebar: "#1E2430",
            progress: "#58A6FF",
            progressBackground: "#2D333B",
            tableHeader: "#F8FAFC",
            tableBorder: "#3B4658",
            searchHighlight: "#56D4DD",
            chart1: "#58A6FF",
            chart2: "#3FB950",
            chart3: "#D29922",
            chart4: "#F85149",
            chart5: "#BC8CFF"
        }
    },
    {
        id: "midnight",
        name: "DevForgeKit Midnight",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Deep blue high-contrast modern theme",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#0a0e27",
            surface: "#111636",
            surfaceAlt: "#1a2147",
            text: "#c8d3f5",
            textMuted: "#6b7ba8",
            textDisabled: "#3d4a6b",
            primary: "#7aa2f7",
            secondary: "#bb9af7",
            accent: "#7aa2f7",
            success: "#9ece6a",
            warning: "#e0af68",
            error: "#f7768e",
            info: "#7dcfff",
            border: "#2a3158",
            borderActive: "#7aa2f7",
            selection: "#283457",
            selectionText: "#c8d3f5",
            header: "#1a2147",
            footer: "#111636",
            sidebar: "#0d1230",
            progress: "#7aa2f7",
            progressBackground: "#1a2147",
            tableHeader: "#7aa2f7",
            tableBorder: "#2a3158",
            searchHighlight: "#e0af68",
            chart1: "#7aa2f7",
            chart2: "#9ece6a",
            chart3: "#e0af68",
            chart4: "#f7768e",
            chart5: "#bb9af7"
        }
    },
    {
        id: "carbon",
        name: "DevForgeKit Carbon",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Near-black with gray accents, enterprise look",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#161616",
            surface: "#1c1c1c",
            surfaceAlt: "#262626",
            text: "#f4f4f4",
            textMuted: "#8d8d8d",
            textDisabled: "#525252",
            primary: "#4589ff",
            secondary: "#8a8a8a",
            accent: "#4589ff",
            success: "#42be65",
            warning: "#ffab00",
            error: "#fa4d56",
            info: "#33b1ff",
            border: "#393939",
            borderActive: "#4589ff",
            selection: "#2a2a2a",
            selectionText: "#f4f4f4",
            header: "#1c1c1c",
            footer: "#161616",
            sidebar: "#121212",
            progress: "#4589ff",
            progressBackground: "#262626",
            tableHeader: "#8d8d8d",
            tableBorder: "#393939",
            searchHighlight: "#ffab00",
            chart1: "#4589ff",
            chart2: "#42be65",
            chart3: "#ffab00",
            chart4: "#fa4d56",
            chart5: "#33b1ff"
        }
    },
    {
        id: "slate",
        name: "DevForgeKit Slate",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Dark gray minimal clean theme",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: undefined,
            surface: undefined,
            surfaceAlt: undefined,
            text: "white",
            textMuted: "gray",
            textDisabled: "#6a6a6a",
            primary: "white",
            secondary: "gray",
            accent: "white",
            success: "green",
            warning: "yellow",
            error: "redBright",
            info: "white",
            border: "gray",
            borderActive: "white",
            selection: "white",
            selectionText: "black",
            header: undefined,
            footer: undefined,
            sidebar: undefined,
            progress: "white",
            progressBackground: "gray",
            tableHeader: "white",
            tableBorder: "gray",
            searchHighlight: "yellow",
            chart1: "white",
            chart2: "green",
            chart3: "yellow",
            chart4: "redBright",
            chart5: "blue"
        }
    },
    {
        id: "nord",
        name: "DevForgeKit Nord",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Blue-gray palette inspired by Nord",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#2e3440",
            surface: "#3b4252",
            surfaceAlt: "#434c5e",
            text: "#e5e9f0",
            textMuted: "#81a1c1",
            textDisabled: "#4c566a",
            primary: "#88c0d0",
            secondary: "#81a1c1",
            accent: "#88c0d0",
            success: "#a3be8c",
            warning: "#ebcb8b",
            error: "#ff6b80",
            info: "#8fbcbb",
            border: "#4c566a",
            borderActive: "#88c0d0",
            selection: "#434c5e",
            selectionText: "#eceff4",
            header: "#3b4252",
            footer: "#2e3440",
            sidebar: "#2e3440",
            progress: "#88c0d0",
            progressBackground: "#434c5e",
            tableHeader: "#81a1c1",
            tableBorder: "#4c566a",
            searchHighlight: "#ebcb8b",
            chart1: "#88c0d0",
            chart2: "#a3be8c",
            chart3: "#ebcb8b",
            chart4: "#ff6b80",
            chart5: "#81a1c1"
        }
    },
    {
        id: "dracula",
        name: "DevForgeKit Dracula",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Purple accents inspired by Dracula",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#282a36",
            surface: "#33373b",
            surfaceAlt: "#44475a",
            text: "#f8f8f2",
            textMuted: "#9ba0c8",
            textDisabled: "#6272a4",
            primary: "#bd93f9",
            secondary: "#ff79c6",
            accent: "#bd93f9",
            success: "#50fa7b",
            warning: "#ffb86c",
            error: "#ff5555",
            info: "#8be9fd",
            border: "#44475a",
            borderActive: "#bd93f9",
            selection: "#44475a",
            selectionText: "#f8f8f2",
            header: "#33373b",
            footer: "#282a36",
            sidebar: "#21222c",
            progress: "#bd93f9",
            progressBackground: "#44475a",
            tableHeader: "#bd93f9",
            tableBorder: "#44475a",
            searchHighlight: "#ffb86c",
            chart1: "#bd93f9",
            chart2: "#50fa7b",
            chart3: "#ffb86c",
            chart4: "#ff5555",
            chart5: "#8be9fd"
        }
    },
    {
        id: "tokyo-night",
        name: "DevForgeKit Tokyo Night",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Excellent contrast inspired by Tokyo Night",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#1a1b26",
            surface: "#16161e",
            surfaceAlt: "#24283b",
            text: "#c0caf5",
            textMuted: "#9aa5ce",
            textDisabled: "#565f89",
            primary: "#7aa2f7",
            secondary: "#bb9af7",
            accent: "#7aa2f7",
            success: "#9ece6a",
            warning: "#e0af68",
            error: "#f7768e",
            info: "#7dcfff",
            border: "#292e42",
            borderActive: "#7aa2f7",
            selection: "#33467c",
            selectionText: "#c0caf5",
            header: "#24283b",
            footer: "#16161e",
            sidebar: "#1f2335",
            progress: "#7aa2f7",
            progressBackground: "#24283b",
            tableHeader: "#7aa2f7",
            tableBorder: "#292e42",
            searchHighlight: "#e0af68",
            chart1: "#7aa2f7",
            chart2: "#9ece6a",
            chart3: "#e0af68",
            chart4: "#f7768e",
            chart5: "#bb9af7"
        }
    },
    {
        id: "one-dark",
        name: "DevForgeKit One Dark",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Inspired by VS Code One Dark",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#282c34",
            surface: "#21252b",
            surfaceAlt: "#2c313a",
            text: "#abb2bf",
            textMuted: "#9ca5b4",
            textDisabled: "#5c6370",
            primary: "#61afef",
            secondary: "#c678dd",
            accent: "#61afef",
            success: "#98c379",
            warning: "#e5c07b",
            error: "#ff5c5c",
            info: "#56b6c2",
            border: "#3b4048",
            borderActive: "#61afef",
            selection: "#3e4451",
            selectionText: "#abb2bf",
            header: "#2c313a",
            footer: "#21252b",
            sidebar: "#21252b",
            progress: "#61afef",
            progressBackground: "#2c313a",
            tableHeader: "#61afef",
            tableBorder: "#3b4048",
            searchHighlight: "#e5c07b",
            chart1: "#61afef",
            chart2: "#98c379",
            chart3: "#e5c07b",
            chart4: "#e06c75",
            chart5: "#c678dd"
        }
    },
    {
        id: "catppuccin-mocha",
        name: "DevForgeKit Catppuccin Mocha",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Warm dark with pastel accents",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#1e1e2e",
            surface: "#181825",
            surfaceAlt: "#313244",
            text: "#cdd6f4",
            textMuted: "#a5adce",
            textDisabled: "#7f849c",
            primary: "#cba6f7",
            secondary: "#f5c2e7",
            accent: "#cba6f7",
            success: "#a6e3a1",
            warning: "#f9e2af",
            error: "#f38ba8",
            info: "#89dceb",
            border: "#45475a",
            borderActive: "#cba6f7",
            selection: "#45475a",
            selectionText: "#cdd6f4",
            header: "#181825",
            footer: "#1e1e2e",
            sidebar: "#11111b",
            progress: "#cba6f7",
            progressBackground: "#313244",
            tableHeader: "#cba6f7",
            tableBorder: "#45475a",
            searchHighlight: "#f9e2af",
            chart1: "#cba6f7",
            chart2: "#a6e3a1",
            chart3: "#f9e2af",
            chart4: "#f38ba8",
            chart5: "#89dceb"
        }
    },
    {
        id: "gruvbox-dark",
        name: "DevForgeKit Gruvbox Dark",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Earth tones for comfortable coding",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#282828",
            surface: "#1d2021",
            surfaceAlt: "#3c3836",
            text: "#ebdbb2",
            textMuted: "#bdae93",
            textDisabled: "#928374",
            primary: "#fabd2f",
            secondary: "#fe8019",
            accent: "#fabd2f",
            success: "#b8bb26",
            warning: "#fabd2f",
            error: "#ff5040",
            info: "#83a598",
            border: "#504945",
            borderActive: "#fabd2f",
            selection: "#504945",
            selectionText: "#ebdbb2",
            header: "#3c3836",
            footer: "#1d2021",
            sidebar: "#1d2021",
            progress: "#fabd2f",
            progressBackground: "#3c3836",
            tableHeader: "#fabd2f",
            tableBorder: "#504945",
            searchHighlight: "#fe8019",
            chart1: "#fabd2f",
            chart2: "#b8bb26",
            chart3: "#d3869b",
            chart4: "#fb4934",
            chart5: "#83a598"
        }
    },
    {
        id: "solarized-dark",
        name: "DevForgeKit Solarized Dark",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Professional low eye-strain palette",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#002b36",
            surface: "#073642",
            surfaceAlt: "#0d4351",
            text: "#93a1a1",
            textMuted: "#93a1a1",
            textDisabled: "#586e75",
            primary: "#4ab8ff",
            secondary: "#6c71c4",
            accent: "#4ab8ff",
            success: "#859900",
            warning: "#b58900",
            error: "#ff4d4d",
            info: "#2aa198",
            border: "#586e75",
            borderActive: "#268bd2",
            selection: "#073642",
            selectionText: "#eee8d5",
            header: "#073642",
            footer: "#002b36",
            sidebar: "#003641",
            progress: "#268bd2",
            progressBackground: "#073642",
            tableHeader: "#268bd2",
            tableBorder: "#586e75",
            searchHighlight: "#b58900",
            chart1: "#268bd2",
            chart2: "#859900",
            chart3: "#b58900",
            chart4: "#dc322f",
            chart5: "#6c71c4"
        }
    },
    {
        id: "github-dark",
        name: "DevForgeKit GitHub Dark",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Inspired by GitHub Dark",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#0d1117",
            surface: "#161b22",
            surfaceAlt: "#21262d",
            text: "#e6edf3",
            textMuted: "#7d8590",
            textDisabled: "#484f58",
            primary: "#2f81f7",
            secondary: "#a371f7",
            accent: "#2f81f7",
            success: "#3fb950",
            warning: "#d29922",
            error: "#f85149",
            info: "#2f81f7",
            border: "#30363d",
            borderActive: "#2f81f7",
            selection: "#1f6feb",
            selectionText: "#e6edf3",
            header: "#161b22",
            footer: "#0d1117",
            sidebar: "#0d1117",
            progress: "#2f81f7",
            progressBackground: "#21262d",
            tableHeader: "#2f81f7",
            tableBorder: "#30363d",
            searchHighlight: "#d29922",
            chart1: "#2f81f7",
            chart2: "#3fb950",
            chart3: "#d29922",
            chart4: "#f85149",
            chart5: "#a371f7"
        }
    },
    {
        id: "matrix",
        name: "DevForgeKit Matrix",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Black background green terminal retro",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#000000",
            surface: "#0a0a0a",
            surfaceAlt: "#111111",
            text: "#00ff41",
            textMuted: "#008f11",
            textDisabled: "#003b00",
            primary: "#00ff41",
            secondary: "#008f11",
            accent: "#00ff41",
            success: "#00ff41",
            warning: "#39ff14",
            error: "#ff0040",
            info: "#00ff41",
            border: "#008f11",
            borderActive: "#00ff41",
            selection: "#003b00",
            selectionText: "#00ff41",
            header: "#0a0a0a",
            footer: "#000000",
            sidebar: "#000000",
            progress: "#00ff41",
            progressBackground: "#003b00",
            tableHeader: "#00ff41",
            tableBorder: "#008f11",
            searchHighlight: "#39ff14",
            chart1: "#00ff41",
            chart2: "#008f11",
            chart3: "#39ff14",
            chart4: "#ff0040",
            chart5: "#0affef"
        }
    },
    {
        id: "cyberpunk",
        name: "DevForgeKit Cyberpunk",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Purple cyan pink high contrast",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#0d0221",
            surface: "#190a2e",
            surfaceAlt: "#2a0b3d",
            text: "#f0f0ff",
            textMuted: "#8b7bb5",
            textDisabled: "#4a3a6b",
            primary: "#ff00ff",
            secondary: "#00ffff",
            accent: "#ff00ff",
            success: "#00ff9f",
            warning: "#ffcc00",
            error: "#ff003c",
            info: "#00ffff",
            border: "#4a1a6b",
            borderActive: "#ff00ff",
            selection: "#2a0b3d",
            selectionText: "#ff00ff",
            header: "#190a2e",
            footer: "#0d0221",
            sidebar: "#0d0221",
            progress: "#ff00ff",
            progressBackground: "#2a0b3d",
            tableHeader: "#ff00ff",
            tableBorder: "#4a1a6b",
            searchHighlight: "#00ffff",
            chart1: "#ff00ff",
            chart2: "#00ffff",
            chart3: "#ffcc00",
            chart4: "#ff003c",
            chart5: "#00ff9f"
        }
    },
    {
        id: "sapphire",
        name: "DevForgeKit Sapphire",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Blue focused professional",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#0c1a2e",
            surface: "#112640",
            surfaceAlt: "#1a3358",
            text: "#d4e4ff",
            textMuted: "#6b8aad",
            textDisabled: "#3a5680",
            primary: "#4a9eff",
            secondary: "#7ab8ff",
            accent: "#4a9eff",
            success: "#42d6a0",
            warning: "#ffb347",
            error: "#ff5c5c",
            info: "#5cb8ff",
            border: "#2a4a6b",
            borderActive: "#4a9eff",
            selection: "#1a3358",
            selectionText: "#d4e4ff",
            header: "#112640",
            footer: "#0c1a2e",
            sidebar: "#0a1626",
            progress: "#4a9eff",
            progressBackground: "#1a3358",
            tableHeader: "#4a9eff",
            tableBorder: "#2a4a6b",
            searchHighlight: "#ffb347",
            chart1: "#4a9eff",
            chart2: "#42d6a0",
            chart3: "#ffb347",
            chart4: "#ff5c5c",
            chart5: "#7ab8ff"
        }
    },
    {
        id: "emerald",
        name: "DevForgeKit Emerald",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Green focused minimal",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#0a1f14",
            surface: "#0e2818",
            surfaceAlt: "#143524",
            text: "#d4f5e0",
            textMuted: "#8ab89a",
            textDisabled: "#5a8a6b",
            primary: "#42d6a0",
            secondary: "#8ae6c1",
            accent: "#42d6a0",
            success: "#42d6a0",
            warning: "#d4d65f",
            error: "#ff6b6b",
            info: "#6bcfff",
            border: "#1f4a33",
            borderActive: "#42d6a0",
            selection: "#143524",
            selectionText: "#d4f5e0",
            header: "#0e2818",
            footer: "#0a1f14",
            sidebar: "#081a10",
            progress: "#42d6a0",
            progressBackground: "#143524",
            tableHeader: "#42d6a0",
            tableBorder: "#1f4a33",
            searchHighlight: "#d4d65f",
            chart1: "#42d6a0",
            chart2: "#8ae6c1",
            chart3: "#d4d65f",
            chart4: "#ff6b6b",
            chart5: "#6bcfff"
        }
    },
    {
        id: "crimson",
        name: "DevForgeKit Crimson",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Dark with red accents",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#1a0a0a",
            surface: "#240e0e",
            surfaceAlt: "#341414",
            text: "#f5d4d4",
            textMuted: "#b08888",
            textDisabled: "#8a5a5a",
            primary: "#e63946",
            secondary: "#ff6b6b",
            accent: "#e63946",
            success: "#52b788",
            warning: "#f4a261",
            error: "#e63946",
            info: "#a8dadc",
            border: "#3d1a1a",
            borderActive: "#e63946",
            selection: "#341414",
            selectionText: "#f5d4d4",
            header: "#240e0e",
            footer: "#1a0a0a",
            sidebar: "#140808",
            progress: "#e63946",
            progressBackground: "#341414",
            tableHeader: "#e63946",
            tableBorder: "#3d1a1a",
            searchHighlight: "#f4a261",
            chart1: "#e63946",
            chart2: "#52b788",
            chart3: "#f4a261",
            chart4: "#ff6b6b",
            chart5: "#a8dadc"
        }
    },
    {
        id: "arctic",
        name: "DevForgeKit Arctic",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Very light theme for bright environments",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#f0f4f8",
            surface: "#e1e8ed",
            surfaceAlt: "#d1dae0",
            text: "#1a2a3a",
            textMuted: "#4a5a6a",
            textDisabled: "#a0b0c0",
            primary: "#0a58ca",
            secondary: "#7c4dff",
            accent: "#0a58ca",
            success: "#2e7d32",
            warning: "#a04500",
            error: "#c62828",
            info: "#0169a0",
            border: "#b0bec5",
            borderActive: "#2196f3",
            selection: "#bbdefb",
            selectionText: "#1a2a3a",
            header: "#e1e8ed",
            footer: "#f0f4f8",
            sidebar: "#e8eef3",
            progress: "#2196f3",
            progressBackground: "#d1dae0",
            tableHeader: "#2196f3",
            tableBorder: "#b0bec5",
            searchHighlight: "#f57c00",
            chart1: "#2196f3",
            chart2: "#2e7d32",
            chart3: "#f57c00",
            chart4: "#c62828",
            chart5: "#7c4dff"
        }
    },
    {
        id: "github-light",
        name: "DevForgeKit GitHub Light",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Professional light inspired by GitHub Light",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#ffffff",
            surface: "#f6f8fa",
            surfaceAlt: "#eaeef2",
            text: "#1f2328",
            textMuted: "#636c76",
            textDisabled: "#afb8c1",
            primary: "#0969da",
            secondary: "#8250df",
            accent: "#0969da",
            success: "#1a7f37",
            warning: "#9a6700",
            error: "#cf222e",
            info: "#0969da",
            border: "#d0d7de",
            borderActive: "#0969da",
            selection: "#ddf4ff",
            selectionText: "#1f2328",
            header: "#f6f8fa",
            footer: "#ffffff",
            sidebar: "#f6f8fa",
            progress: "#0969da",
            progressBackground: "#eaeef2",
            tableHeader: "#0969da",
            tableBorder: "#d0d7de",
            searchHighlight: "#9a6700",
            chart1: "#0969da",
            chart2: "#1a7f37",
            chart3: "#9a6700",
            chart4: "#cf222e",
            chart5: "#8250df"
        }
    },
    {
        id: "paper",
        name: "DevForgeKit Paper",
        author: "DevForgeKit",
        version: "1.0.0",
        description: "Warm light theme for comfortable reading",
        homepage: "https://github.com/NouradinAbdurahman/DevForgeKit",
        license: "MIT",
        colors: {
            background: "#fdf6e3",
            surface: "#eee8d5",
            surfaceAlt: "#e4dcc4",
            text: "#3a3530",
            textMuted: "#5a5248",
            textDisabled: "#b5ad9e",
            primary: "#a03a10",
            secondary: "#6c71c4",
            accent: "#a03a10",
            success: "#566800",
            warning: "#8a6700",
            error: "#b22a25",
            info: "#1a6a9a",
            border: "#c9c1a8",
            borderActive: "#cb4b16",
            selection: "#eee8d5",
            selectionText: "#3a3530",
            header: "#eee8d5",
            footer: "#fdf6e3",
            sidebar: "#f5efe0",
            progress: "#cb4b16",
            progressBackground: "#e4dcc4",
            tableHeader: "#cb4b16",
            tableBorder: "#c9c1a8",
            searchHighlight: "#b58900",
            chart1: "#cb4b16",
            chart2: "#7a8c00",
            chart3: "#b58900",
            chart4: "#dc322f",
            chart5: "#268bd2"
        }
    }
];
