// ASP.NET generator (v1.2.2 Tier 2): scaffolds via the official
// `dotnet new webapi`, then layers Docker and CI.
import { runShellCommand } from "../core/shell.js";
import { confirm } from "../lib/prompts.js";
import { vscodeSettings, vscodeExtensions } from "./shared.js";

async function promptOptions(flags) {
    const docker = flags.docker ?? await confirm("Include a Dockerfile?", true);
    return { docker };
}

function dockerfile(name) {
    return `FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 8080
ENTRYPOINT ["dotnet", "${name}.dll"]
`;
}

function ciWorkflow() {
    return `name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build --verbosity normal
`;
}

export const aspnetGenerator = {
    id: "aspnet",
    label: "ASP.NET",
    description: "Web API scaffolded via the official dotnet CLI, Docker, CI",
    requiresTool: { command: "dotnet", hint: "Install the .NET SDK - see https://dotnet.microsoft.com/download" },
    promptOptions,

    async scaffold({ name, parentDir }) {
        return runShellCommand(`dotnet new webapi -n "${name}" -o "${name}"`, { cwd: parentDir });
    },

    generate({ name, options }) {
        const files = [
            { path: ".vscode/settings.json", content: vscodeSettings({ "omnisharp.enableEditorConfigSupport": true }) },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["ms-dotnettools.csdevkit"]) },
            { path: ".github/workflows/ci.yml", content: ciWorkflow() },
            {
                path: "README.devforgekit.md",
                content: `# ${name} - DevForgeKit notes\n\nThis ASP.NET Web API was generated by \`devforgekit new aspnet\` via \`dotnet new webapi\`.\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`dotnet run\` | Run the dev server |\n| \`dotnet test\` | Run tests |\n${options.docker ? "| `docker build -t " + name + " .` | Build a production image |\n" : ""}\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];
        if (options.docker) {
            files.push({ path: "Dockerfile", content: dockerfile(name) }, { path: ".dockerignore", content: "bin\nobj\n.git\n" });
        }
        return files;
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "dotnet run"];
    }
};
