// Django generator (v1.2.2 Tier 2): scaffolds with the official
// `django-admin startproject`, then layers requirements.txt, Docker,
// CI, and editor config - django-admin itself doesn't manage
// dependencies or containerization.
import { runShellCommand } from "../core/shell.js";
import { confirm } from "../lib/prompts.js";
import { EDITORCONFIG, vscodeSettings, vscodeExtensions } from "./shared.js";

// gitignorePython() - `django-admin startproject` writes no .gitignore
// at all (unlike e.g. Laravel/Spring Boot's scaffolders), and this
// generator didn't add one either - a real gap found auditing every
// generator for v2.1.2.
function gitignorePython() {
    return `__pycache__/
*.py[cod]
.venv/
venv/
.env
db.sqlite3
staticfiles/
media/
.pytest_cache/
.ruff_cache/
*.egg-info/
.DS_Store
`;
}

async function promptOptions(flags) {
    const docker = flags.docker ?? await confirm("Include Docker + docker-compose (app + Postgres)?", true);
    return { docker };
}

function requirementsTxt() {
    return `Django>=5.1,<6.0
python-dotenv>=1.0.1
`;
}

function requirementsDevTxt() {
    return `pytest-django>=4.9.0
ruff>=0.7.0
`;
}

function dockerfile() {
    return `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
`;
}

function dockerCompose(name) {
    const dbName = name.replace(/-/g, "_");
    return `services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/${dbName}
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${dbName}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
`;
}

function ciWorkflow() {
    return `name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: ruff check .
      - run: python manage.py test
`;
}

export const djangoGenerator = {
    id: "django",
    label: "Django",
    description: "Scaffolded via django-admin, plus requirements.txt, Docker, CI",
    tags: ["backend", "python", "web", "api"],
    recommends: ["postgres", "poetry", "docker"],
    requiresTool: { command: "django-admin", hint: "Install it with: pip install django" },
    promptOptions,

    async scaffold({ name, parentDir }) {
        return runShellCommand(`django-admin startproject "${name}" "${name}"`, { cwd: parentDir });
    },

    generate({ name, options }) {
        const files = [
            { path: "requirements.txt", content: requirementsTxt() },
            { path: "requirements-dev.txt", content: requirementsDevTxt() },
            { path: ".env.example", content: "DEBUG=true\nSECRET_KEY=change-me\n" },
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".gitignore", content: gitignorePython() },
            { path: ".vscode/settings.json", content: vscodeSettings({ "python.analysis.typeCheckingMode": "basic" }) },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["ms-python.python", "charliermarsh.ruff"]) },
            { path: ".github/workflows/ci.yml", content: ciWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nA Django project generated by \`devforgekit new django\` via \`django-admin startproject\`.\n\n## Getting started\n\n\`\`\`bash\npython -m venv .venv && source .venv/bin/activate\npip install -r requirements.txt -r requirements-dev.txt\ncp .env.example .env\npython manage.py migrate\npython manage.py runserver\n\`\`\`\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`python manage.py runserver\` | Run the dev server |\n| \`python manage.py test\` | Run tests |\n| \`ruff check .\` | Lint |\n${options.docker ? "| `docker compose up --build` | Run app + Postgres in containers |\n" : ""}\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];

        if (options.docker) {
            files.push(
                { path: "Dockerfile", content: dockerfile() },
                { path: "docker-compose.yml", content: dockerCompose(name) },
                { path: ".dockerignore", content: "__pycache__\n.venv\n.git\n.env\n" }
            );
        }

        return files;
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "python -m venv .venv && source .venv/bin/activate", "pip install -r requirements.txt -r requirements-dev.txt", "python manage.py migrate", "python manage.py runserver"];
    }
};
