// Electron generator (v1.2.2 Tier 2): fully hand-written rather than
// shelling out to `create-electron-app` - Electron Forge's generator
// changes its interactive/flag surface often enough between versions
// that a hand-rolled, minimal-but-correct main/preload/renderer skeleton
// is more reliable to keep working than chasing that CLI's current flags.
import { mitLicense, EDITORCONFIG, vscodeSettings, vscodeExtensions } from "./shared.js";

function packageJson(name) {
    return `${JSON.stringify({
        name,
        version: "0.1.0",
        private: true,
        main: "src/main.js",
        scripts: {
            start: "electron .",
            package: "electron-builder"
        },
        devDependencies: {
            electron: "^33.2.1",
            "electron-builder": "^25.1.8"
        }
    }, null, 2)}\n`;
}

function mainJs() {
    return `const { app, BrowserWindow } = require("electron");
const path = require("node:path");

function createWindow() {
    const win = new BrowserWindow({
        width: 1000,
        height: 700,
        webPreferences: {
            preload: path.join(__dirname, "preload.js"),
            contextIsolation: true,
            nodeIntegration: false
        }
    });
    win.loadFile(path.join(__dirname, "renderer", "index.html"));
}

app.whenReady().then(() => {
    createWindow();
    app.on("activate", () => {
        if (BrowserWindow.getAllWindows().length === 0) createWindow();
    });
});

app.on("window-all-closed", () => {
    if (process.platform !== "darwin") app.quit();
});
`;
}

function preloadJs() {
    return `const { contextBridge } = require("electron");

contextBridge.exposeInMainWorld("app", {
    version: process.versions.electron
});
`;
}

function indexHtml(name) {
    return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${name}</title>
  </head>
  <body>
    <h1>${name}</h1>
    <p>Electron version: <span id="version"></span></p>
    <script src="renderer.js"></script>
  </body>
</html>
`;
}

function rendererJs() {
    return `document.getElementById("version").textContent = window.app.version;
`;
}

function ciWorkflow() {
    return `name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - run: npm ci
      - run: npm run lint --if-present
`;
}

export const electronGenerator = {
    id: "electron",
    label: "Electron",
    description: "Desktop app: main/preload/renderer skeleton, electron-builder packaging, CI",
    requiresTool: null,

    generate({ name }) {
        return [
            { path: "package.json", content: packageJson(name) },
            { path: "src/main.js", content: mainJs() },
            { path: "src/preload.js", content: preloadJs() },
            { path: "src/renderer/index.html", content: indexHtml(name) },
            { path: "src/renderer/renderer.js", content: rendererJs() },
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".gitignore", content: "node_modules/\nout/\ndist/\n.DS_Store\n" },
            { path: "LICENSE", content: mitLicense() },
            { path: ".vscode/settings.json", content: vscodeSettings() },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["dbaeumer.vscode-eslint"]) },
            { path: ".github/workflows/ci.yml", content: ciWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nAn Electron desktop app generated by \`devforgekit new electron\` (main/preload/renderer skeleton).\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`npm start\` | Launch the app |\n| \`npm run package\` | Package a distributable with electron-builder |\n\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "npm install", "npm start"];
    }
};
