// Expo generator (v1.2.2 Tier 2): scaffolds with the official
// `create-expo-app` (TypeScript template), then layers CI and editor
// config. Expo is the recommended default for new React Native projects
// today - see generators/react-native.js for the bare-workflow sibling.
import { runShellCommand } from "../core/shell.js";
import { EDITORCONFIG, vscodeSettings, vscodeExtensions, ciNodeWorkflow } from "./shared.js";

export const expoGenerator = {
    id: "expo",
    label: "Expo",
    description: "Managed React Native via Expo (TypeScript template), CI",
    tags: ["mobile", "react-native", "javascript", "js", "ios", "android"],
    recommends: ["android-studio", "fastlane"],
    requiresTool: { command: "npx", hint: "Install Node.js (e.g. `devforgekit component install node`), which ships npx." },
    compatibilityCheck: ["node", "watchman"],

    async scaffold({ name, parentDir }) {
        return runShellCommand(`npx --yes create-expo-app@latest "${name}" --template blank-typescript`, { cwd: parentDir });
    },

    generate({ name }) {
        return [
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".vscode/settings.json", content: vscodeSettings() },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["msjsdiag.vscode-react-native", "esbenp.prettier-vscode"]) },
            { path: ".github/workflows/ci.yml", content: ciNodeWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nAn Expo (React Native) app generated by \`devforgekit new expo\`.\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpx expo start\n\`\`\`\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`npx expo start\` | Start the Metro dev server |\n| \`npx expo run:ios\` | Run on iOS simulator |\n| \`npx expo run:android\` | Run on Android emulator |\n\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "npm install", "npx expo start"];
    }
};
