// FastAPI generator (v1.2.2 Tier 2): fully hand-written, richer than the
// static templates/fastapi starter (which stays as-is for `cp -r` users
// per docs/Templates.md) - adds a real app package layout, Pydantic
// settings, pytest, Docker, and CI.
import { confirm } from "../lib/prompts.js";
import { mitLicense, EDITORCONFIG, vscodeSettings, vscodeExtensions } from "./shared.js";

async function promptOptions(flags) {
    const docker = flags.docker ?? await confirm("Include Docker + docker-compose?", true);
    return { docker };
}

function mainPy() {
    return `from fastapi import FastAPI

from app.api.routes import health
from app.core.config import get_settings

settings = get_settings()

app = FastAPI(title=settings.app_name)

app.include_router(health.router, prefix="/health", tags=["health"])
`;
}

function configPy(name) {
    return `from functools import lru_cache

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    app_name: str = "${name}"
    debug: bool = False

    class Config:
        env_file = ".env"


@lru_cache
def get_settings() -> Settings:
    return Settings()
`;
}

function healthRoute() {
    return `from fastapi import APIRouter

router = APIRouter()


@router.get("")
def health_check() -> dict:
    return {"status": "ok"}
`;
}

function testHealth() {
    return `from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_health() -> None:
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}
`;
}

function requirementsTxt() {
    return `fastapi>=0.115.0
uvicorn[standard]>=0.32.0
pydantic-settings>=2.6.0
python-dotenv>=1.0.1
`;
}

function requirementsDevTxt() {
    return `pytest>=8.3.0
httpx>=0.27.0
ruff>=0.7.0
`;
}

function dockerfile() {
    return `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
}

function dockerCompose(name) {
    return `services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=${name}
`;
}

function ciWorkflow() {
    return `name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: ruff check .
      - run: pytest
`;
}

export const fastapiGenerator = {
    id: "fastapi",
    label: "FastAPI",
    description: "Pydantic settings, pytest, Docker, CI",
    requiresTool: null,
    promptOptions,

    generate({ name, options }) {
        const files = [
            { path: "app/__init__.py", content: "" },
            { path: "app/main.py", content: mainPy() },
            { path: "app/core/__init__.py", content: "" },
            { path: "app/core/config.py", content: configPy(name) },
            { path: "app/api/__init__.py", content: "" },
            { path: "app/api/routes/__init__.py", content: "" },
            { path: "app/api/routes/health.py", content: healthRoute() },
            { path: "tests/__init__.py", content: "" },
            { path: "tests/test_health.py", content: testHealth() },
            { path: "requirements.txt", content: requirementsTxt() },
            { path: "requirements-dev.txt", content: requirementsDevTxt() },
            { path: ".env.example", content: `APP_NAME=${name}\nDEBUG=false\n` },
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".gitignore", content: "__pycache__/\n*.pyc\n.venv/\nenv/\n.env\n.pytest_cache/\n.ruff_cache/\n.DS_Store\n" },
            { path: "LICENSE", content: mitLicense() },
            { path: ".vscode/settings.json", content: vscodeSettings({ "python.analysis.typeCheckingMode": "basic" }) },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["ms-python.python", "charliermarsh.ruff"]) },
            { path: ".github/workflows/ci.yml", content: ciWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nA FastAPI service generated by \`devforgekit new fastapi\`.\n\n## Getting started\n\n\`\`\`bash\npython -m venv .venv && source .venv/bin/activate\npip install -r requirements.txt -r requirements-dev.txt\ncp .env.example .env\nuvicorn app.main:app --reload\n\`\`\`\n\nOpen http://localhost:8000/docs for the interactive OpenAPI docs (built into FastAPI).\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`uvicorn app.main:app --reload\` | Run the dev server |\n| \`pytest\` | Run tests |\n| \`ruff check .\` | Lint |\n${options.docker ? "| `docker compose up --build` | Run in a container |\n" : ""}\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];

        if (options.docker) {
            files.push(
                { path: "Dockerfile", content: dockerfile() },
                { path: "docker-compose.yml", content: dockerCompose(name) },
                { path: ".dockerignore", content: "__pycache__\n.venv\n.git\n.env\n" }
            );
        }

        return files;
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "python -m venv .venv && source .venv/bin/activate", "pip install -r requirements.txt -r requirements-dev.txt", "uvicorn app.main:app --reload"];
    }
};
