// Flutter generator (v1.2.2 Tier 1): scaffolds with the official
// `flutter create` (the only reliable way to get correct iOS/Android/web
// platform folders - hand-writing Gradle/Xcode project files would be
// enormous and fragile), then replaces the generated lib/ with a Clean
// Architecture layout, adds the chosen state-management/backend
// dependencies, CI, linting, a real widget test, and an optional Docker
// build (serves `flutter build web` output via nginx).
import { runShellCommand } from "../core/shell.js";
import { select, confirm } from "../lib/prompts.js";
import { vscodeSettings, vscodeExtensions } from "./shared.js";

async function promptOptions(flags) {
    const state = flags.state || await select("State management?", [
        { title: "Riverpod", value: "riverpod" },
        { title: "Bloc", value: "bloc" },
        { title: "None (setState only)", value: "none" }
    ]);
    const backend = flags.backend || await select("Backend?", [
        { title: "Supabase", value: "supabase" },
        { title: "Firebase", value: "firebase" },
        { title: "None", value: "none" }
    ]);
    const docker = flags.docker ?? await confirm("Include Docker (serves the web build via nginx)?", false);
    return { state, backend, docker };
}

function pubspecYaml({ name, options }) {
    const deps = ["  flutter:\n    sdk: flutter", "  cupertino_icons: ^1.0.8"];
    if (options.state === "riverpod") deps.push("  flutter_riverpod: ^2.6.1");
    if (options.state === "bloc") { deps.push("  flutter_bloc: ^8.1.6"); deps.push("  equatable: ^2.0.7"); }
    if (options.backend === "supabase") deps.push("  supabase_flutter: ^2.8.0");
    if (options.backend === "firebase") { deps.push("  firebase_core: ^3.8.0"); deps.push("  cloud_firestore: ^5.5.0"); }

    return `name: ${name.replace(/-/g, "_")}
description: "A Flutter project generated by devforgekit new flutter."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
${deps.join("\n")}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
`;
}

function analysisOptions() {
    return `include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
`;
}

function mainDart({ name, options }) {
    const providerWrap = options.state === "riverpod";
    return `import 'package:flutter/material.dart';
${providerWrap ? "import 'package:flutter_riverpod/flutter_riverpod.dart';\n" : ""}${options.backend === "supabase" ? "import 'package:supabase_flutter/supabase_flutter.dart';\n" : ""}${options.backend === "firebase" ? "import 'package:firebase_core/firebase_core.dart';\n" : ""}import 'presentation/pages/home_page.dart';

Future<void> main() async {
${options.backend === "supabase" ? "  WidgetsFlutterBinding.ensureInitialized();\n  await Supabase.initialize(url: 'YOUR_SUPABASE_URL', anonKey: 'YOUR_SUPABASE_ANON_KEY');\n" : ""}${options.backend === "firebase" ? "  WidgetsFlutterBinding.ensureInitialized();\n  await Firebase.initializeApp();\n" : ""}  runApp(${providerWrap ? "const ProviderScope(child: " : ""}const ${pascalCase(name)}App()${providerWrap ? ")" : ""});
}

class ${pascalCase(name)}App extends StatelessWidget {
  const ${pascalCase(name)}App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${name}',
      theme: ThemeData(primarySwatch: Colors.blue, useMaterial3: true),
      home: const HomePage(),
    );
  }
}
`;
}

function pascalCase(name) {
    return name.split(/[-_\s]+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}

function counterProviderRiverpod() {
    return `import 'package:flutter_riverpod/flutter_riverpod.dart';

final counterProvider = StateNotifierProvider<CounterNotifier, int>((ref) {
  return CounterNotifier();
});

class CounterNotifier extends StateNotifier<int> {
  CounterNotifier() : super(0);

  void increment() => state++;
}
`;
}

function counterBloc() {
    return `import 'package:flutter_bloc/flutter_bloc.dart';

abstract class CounterEvent {}

class CounterIncremented extends CounterEvent {}

class CounterBloc extends Bloc<CounterEvent, int> {
  CounterBloc() : super(0) {
    on<CounterIncremented>((event, emit) => emit(state + 1));
  }
}
`;
}

function homePage(options) {
    if (options.state === "riverpod") {
        return `import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/counter_provider.dart';

class HomePage extends ConsumerWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final count = ref.watch(counterProvider);
    return Scaffold(
      appBar: AppBar(title: const Text('Home')),
      body: Center(child: Text('Count: $count', key: const Key('counterText'))),
      floatingActionButton: FloatingActionButton(
        onPressed: () => ref.read(counterProvider.notifier).increment(),
        child: const Icon(Icons.add),
      ),
    );
  }
}
`;
    }
    if (options.state === "bloc") {
        return `import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../blocs/counter_bloc.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => CounterBloc(),
      child: Scaffold(
        appBar: AppBar(title: const Text('Home')),
        body: Center(
          child: BlocBuilder<CounterBloc, int>(
            builder: (context, count) => Text('Count: $count', key: const Key('counterText')),
          ),
        ),
        floatingActionButton: Builder(
          builder: (context) => FloatingActionButton(
            onPressed: () => context.read<CounterBloc>().add(CounterIncremented()),
            child: const Icon(Icons.add),
          ),
        ),
      ),
    );
  }
}
`;
    }
    return `import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home')),
      body: Center(child: Text('Count: $_count', key: const Key('counterText'))),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() => _count++),
        child: const Icon(Icons.add),
      ),
    );
  }
}
`;
}

function widgetTest(name, options) {
    const pump = options.state === "riverpod"
        ? `await tester.pumpWidget(const ProviderScope(child: ${pascalCase(name)}App()));`
        : `await tester.pumpWidget(const ${pascalCase(name)}App());`;
    return `import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
${options.state === "riverpod" ? "import 'package:flutter_riverpod/flutter_riverpod.dart';\n" : ""}import 'package:${name.replace(/-/g, "_")}/main.dart';

void main() {
  testWidgets('counter increments when + is tapped', (WidgetTester tester) async {
    ${pump}

    expect(find.text('Count: 0'), findsOneWidget);

    await tester.tap(find.byType(FloatingActionButton));
    await tester.pump();

    expect(find.text('Count: 1'), findsOneWidget);
  });
}
`;
}

function ciWorkflow() {
    return `name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --debug
`;
}

function dockerfile() {
    return `# Serves the Flutter web build via nginx. Build the web bundle first:
#   flutter build web --release
FROM nginx:alpine
COPY build/web /usr/share/nginx/html
EXPOSE 80
`;
}

function serviceStub(name, backend) {
    if (backend === "supabase") {
        return `import 'package:supabase_flutter/supabase_flutter.dart';

/// Thin wrapper around the Supabase client - inject/mock this in tests
/// instead of calling Supabase.instance.client directly from widgets.
class SupabaseService {
  SupabaseClient get client => Supabase.instance.client;
}
`;
    }
    if (backend === "firebase") {
        return `import 'package:cloud_firestore/cloud_firestore.dart';

/// Thin wrapper around Firestore - inject/mock this in tests instead of
/// calling FirebaseFirestore.instance directly from widgets.
class FirestoreService {
  FirebaseFirestore get db => FirebaseFirestore.instance;
}
`;
    }
    return `// No backend selected - this is where a repository implementation
// (data/repositories/) would call out to your API of choice.
`;
}

export const flutterGenerator = {
    id: "flutter",
    label: "Flutter",
    description: "Clean Architecture, Riverpod/Bloc, Supabase/Firebase, CI/CD, testing, linting",
    requiresTool: { command: "flutter", hint: "Install it with: devforgekit component install flutter" },
    compatibilityCheck: ["flutter"],
    promptOptions,

    async scaffold({ name, parentDir, options }) {
        void options;
        return runShellCommand(
            `flutter create --project-name "${name.replace(/-/g, "_")}" --platforms=ios,android,web "${name}"`,
            { cwd: parentDir }
        );
    },

    generate({ name, options }) {
        const files = [
            { path: "pubspec.yaml", content: pubspecYaml({ name, options }) },
            { path: "analysis_options.yaml", content: analysisOptions() },
            { path: "lib/main.dart", content: mainDart({ name, options }) },
            { path: "lib/presentation/pages/home_page.dart", content: homePage(options) },
            { path: "lib/core/error/failures.dart", content: "class Failure {\n  final String message;\n  const Failure(this.message);\n}\n" },
            { path: "lib/core/utils/constants.dart", content: `const appName = '${name}';\n` },
            { path: "lib/domain/entities/.gitkeep", content: "" },
            { path: "lib/domain/repositories/.gitkeep", content: "" },
            { path: "lib/domain/usecases/.gitkeep", content: "" },
            { path: "lib/data/models/.gitkeep", content: "" },
            { path: "lib/data/datasources/.gitkeep", content: "" },
            { path: "lib/data/repositories/service_stub.dart", content: serviceStub(name, options.backend) },
            { path: "test/widget_test.dart", content: widgetTest(name, options) },
            { path: ".github/workflows/ci.yml", content: ciWorkflow() },
            { path: ".vscode/settings.json", content: vscodeSettings({ "dart.lineLength": 100 }) },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["dart-code.dart-code", "dart-code.flutter"]) },
            {
                path: "README.md",
                content: `# ${name}\n\nA Flutter app generated by \`devforgekit new flutter\` with Clean Architecture (\`lib/core\`, \`lib/data\`, \`lib/domain\`, \`lib/presentation\`), ${options.state === "none" ? "no external state management" : options.state} state management, and ${options.backend === "none" ? "no backend" : options.backend} configured.\n\n## Getting started\n\n\`\`\`bash\nflutter pub get\nflutter run\n\`\`\`\n\n## Project structure\n\n\`\`\`text\nlib/\n  core/           # constants, failures, shared utils\n  data/           # models, datasources, repository implementations\n  domain/         # entities, repository interfaces, use cases\n  presentation/   # pages, widgets, ${options.state === "none" ? "state" : options.state}\n\`\`\`\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`flutter run\` | Run on a connected device/emulator |\n| \`flutter test\` | Run the widget test suite |\n| \`flutter analyze\` | Static analysis / linting |\n| \`dart format .\` | Format the codebase |\n${options.docker ? "| `flutter build web --release && docker build -t " + name + " .` | Build and containerize the web target |\n" : ""}\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];

        if (options.state === "riverpod") {
            files.push({ path: "lib/presentation/providers/counter_provider.dart", content: counterProviderRiverpod() });
        }
        if (options.state === "bloc") {
            files.push({ path: "lib/presentation/blocs/counter_bloc.dart", content: counterBloc() });
        }
        if (options.docker) {
            files.push({ path: "Dockerfile", content: dockerfile() });
        }

        return files;
    },

    nextSteps({ name, options }) {
        return [`cd ${name}`, "flutter pub get", "flutter run", ...(options.docker ? ["flutter build web --release", `docker build -t ${name} .`] : [])];
    }
};
