// Go Fiber generator (v1.2.2 Tier 2): fully hand-written - a Go Fiber
// project is just a go.mod + a handful of .go files, so generating them
// directly is simpler and more reliable than shelling out to anything.
// `go mod tidy` is run automatically if `go` is on PATH (fills in
// go.sum); otherwise the user runs it themselves - either way, the
// generated go.mod is already correct.
import { commandExists, runShellCommand } from "../core/shell.js";
import { mitLicense, EDITORCONFIG, vscodeSettings, vscodeExtensions } from "./shared.js";

function goMod(name) {
    return `module ${name}

go 1.23

require github.com/gofiber/fiber/v2 v2.52.5
`;
}

function mainGo() {
    return `package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok"})
	})

	log.Fatal(app.Listen(":3000"))
}
`;
}

function mainTestGo() {
    return `package main

import (
	"net/http/httptest"
	"testing"

	"github.com/gofiber/fiber/v2"
)

func TestHealth(t *testing.T) {
	app := fiber.New()
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok"})
	})

	req := httptest.NewRequest("GET", "/health", nil)
	resp, err := app.Test(req)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.StatusCode != 200 {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}
`;
}

function dockerfile(name) {
    return `FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN go build -o /${name} .

FROM alpine:3.20
COPY --from=builder /${name} /${name}
EXPOSE 3000
CMD ["/${name}"]
`;
}

function ciWorkflow() {
    return `name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - run: go vet ./...
      - run: go build ./...
      - run: go test ./...
`;
}

export const goFiberGenerator = {
    id: "go-fiber",
    label: "Go Fiber",
    description: "Go + Fiber web framework, tests, Docker, CI",
    requiresTool: null,

    generate({ name, dir }) {
        void dir;
        return [
            { path: "go.mod", content: goMod(name) },
            { path: "main.go", content: mainGo() },
            { path: "main_test.go", content: mainTestGo() },
            { path: "Dockerfile", content: dockerfile(name) },
            { path: ".dockerignore", content: "*.md\n.git\n.github\n" },
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".gitignore", content: `/${name}\n*.exe\n.env\n.DS_Store\n` },
            { path: "LICENSE", content: mitLicense() },
            { path: ".vscode/settings.json", content: vscodeSettings({ "go.formatTool": "gofmt" }) },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["golang.go"]) },
            { path: ".github/workflows/ci.yml", content: ciWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nA Go Fiber API generated by \`devforgekit new go-fiber\`.\n\n## Getting started\n\n\`\`\`bash\ngo mod tidy\ngo run .\n\`\`\`\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`go run .\` | Run the server |\n| \`go test ./...\` | Run tests |\n| \`go vet ./...\` | Static analysis |\n| \`docker build -t ${name} .\` | Build a production image |\n\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];
    },

    async postGenerate({ dir }) {
        if (await commandExists("go")) {
            await runShellCommand("go mod tidy", { cwd: dir, silent: true });
        }
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "go mod tidy", "go run ."];
    }
};
