// Laravel generator (v1.2.2 Tier 2): scaffolds with the official
// `composer create-project laravel/laravel`, then layers Docker and CI -
// Laravel's own installer already handles .env/.gitignore/testing setup,
// so there's little to add on top beyond containerization.
import { runShellCommand } from "../core/shell.js";
import { confirm } from "../lib/prompts.js";
import { vscodeSettings, vscodeExtensions } from "./shared.js";

async function promptOptions(flags) {
    const docker = flags.docker ?? await confirm("Include Docker (php-fpm + nginx)?", true);
    return { docker };
}

function dockerfile() {
    return `FROM php:8.3-fpm-alpine
RUN apk add --no-cache libpng-dev libzip-dev zip unzip \\
    && docker-php-ext-install pdo_mysql zip gd
WORKDIR /var/www
COPY . .
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev --optimize-autoloader
EXPOSE 9000
CMD ["php-fpm"]
`;
}

function nginxConf() {
    return `server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \\.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
`;
}

function dockerCompose() {
    return `services:
  app:
    build: .
    volumes:
      - .:/var/www

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
`;
}

function ciWorkflow() {
    return `name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - run: composer install --no-interaction --prefer-dist
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: php artisan test
`;
}

export const laravelGenerator = {
    id: "laravel",
    label: "Laravel",
    description: "Scaffolded via composer create-project laravel/laravel, plus Docker and CI",
    requiresTool: { command: "composer", hint: "Install PHP + Composer first - see https://getcomposer.org/download/" },
    promptOptions,

    async scaffold({ name, parentDir }) {
        return runShellCommand(`composer create-project laravel/laravel "${name}"`, { cwd: parentDir });
    },

    generate({ name, options }) {
        const files = [
            { path: ".vscode/settings.json", content: vscodeSettings({ "editor.formatOnSave": false }) },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["bmewburn.vscode-intelephense-client", "onecentlin.laravel-blade"]) },
            { path: ".github/workflows/ci.yml", content: ciWorkflow() },
            {
                path: "README.devforgekit.md",
                content: `# ${name} - DevForgeKit notes\n\nThis Laravel project was generated by \`devforgekit new laravel\` via the official \`composer create-project laravel/laravel\` installer - see \`README.md\` for Laravel's own documentation.\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`php artisan serve\` | Run the dev server |\n| \`php artisan test\` | Run tests |\n${options.docker ? "| `docker compose up --build` then visit http://localhost:8080 | Run via php-fpm + nginx |\n" : ""}\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];

        if (options.docker) {
            files.push(
                { path: "Dockerfile", content: dockerfile() },
                { path: "docker-compose.yml", content: dockerCompose() },
                { path: "docker/nginx.conf", content: nginxConf() }
            );
        }

        return files;
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "composer install", "php artisan serve"];
    }
};
