// NestJS generator (v1.2.2 Tier 2): scaffolds with the official Nest CLI
// (`nest new`), then layers Docker, CI, and editor config.
import { runShellCommand } from "../core/shell.js";
import { confirm } from "../lib/prompts.js";
import { EDITORCONFIG, vscodeSettings, vscodeExtensions, ciNodeWorkflow, dockerignoreNode } from "./shared.js";

async function promptOptions(flags) {
    const docker = flags.docker ?? await confirm("Include a Dockerfile?", true);
    return { docker };
}

function dockerfile() {
    // `npm install`, not `npm ci`: scaffold() below passes --skip-install
    // so no package-lock.json exists right after generation - `npm ci`
    // would fail on a fresh project's first `docker build`.
    return `FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/main"]
`;
}

export const nestjsGenerator = {
    id: "nestjs",
    label: "NestJS",
    description: "NestJS API scaffolded via the official Nest CLI, Docker, CI",
    requiresTool: { command: "npx", hint: "Install Node.js (e.g. `devforgekit component install node`), which ships npx." },
    promptOptions,

    async scaffold({ name, parentDir }) {
        return runShellCommand(
            `npx --yes @nestjs/cli new "${name}" --package-manager npm --skip-git --skip-install`,
            { cwd: parentDir }
        );
    },

    generate({ name, options }) {
        const files = [
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".vscode/settings.json", content: vscodeSettings() },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["dbaeumer.vscode-eslint", "esbenp.prettier-vscode"]) },
            { path: ".github/workflows/ci.yml", content: ciNodeWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nA NestJS API generated by \`devforgekit new nestjs\` via the official Nest CLI.\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm run start:dev\n\`\`\`\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`npm run start:dev\` | Start with watch mode |\n| \`npm run build\` | Production build |\n| \`npm test\` | Unit tests (Jest) |\n| \`npm run test:e2e\` | End-to-end tests |\n${options.docker ? "| `docker build -t " + name + " .` | Build a production image |\n" : ""}\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];
        if (options.docker) {
            files.push({ path: "Dockerfile", content: dockerfile() }, { path: ".dockerignore", content: dockerignoreNode() });
        }
        return files;
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "npm install", "npm run start:dev"];
    }
};
