// React Native (bare workflow) generator (v1.2.2 Tier 2): scaffolds with
// Expo's official `bare-minimum` template rather than the legacy
// `react-native init` - it produces the same real native ios/ and
// android/ folders, but through a CLI that's actively maintained and far
// more reliable non-interactively. The generated app does not depend on
// Expo Go or EAS - it's plain React Native. See generators/expo.js for
// the managed-workflow sibling.
import { runShellCommand } from "../core/shell.js";
import { EDITORCONFIG, vscodeSettings, vscodeExtensions, ciNodeWorkflow } from "./shared.js";

export const reactNativeGenerator = {
    id: "react-native",
    label: "React Native",
    description: "Bare-workflow React Native (native ios/android folders) via Expo's bare-minimum template, CI",
    requiresTool: { command: "npx", hint: "Install Node.js (e.g. `devforgekit component install node`), which ships npx." },
    compatibilityCheck: ["node", "watchman"],

    async scaffold({ name, parentDir }) {
        return runShellCommand(`npx --yes create-expo-app@latest "${name}" --template bare-minimum`, { cwd: parentDir });
    },

    generate({ name }) {
        return [
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".vscode/settings.json", content: vscodeSettings() },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["msjsdiag.vscode-react-native", "esbenp.prettier-vscode"]) },
            { path: ".github/workflows/ci.yml", content: ciNodeWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nA bare-workflow React Native app generated by \`devforgekit new react-native\` (native \`ios/\`/\`android/\` folders, scaffolded via Expo's \`bare-minimum\` template - no Expo Go/EAS dependency).\n\n## Prerequisites\n\n- Xcode (iOS) and/or Android Studio (Android) - see \`devforgekit doctor\`\n- CocoaPods for iOS: \`cd ios && pod install\`\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm run ios     # or: npm run android\n\`\`\`\n\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "npm install", "cd ios && pod install && cd ..", "npm run ios"];
    }
};
