// React generator (v1.2.2 Tier 2): scaffolds with Vite's official
// `react-ts` template - the current standard way to start a plain React
// SPA (Create React App is deprecated upstream) - then layers CI,
// .editorconfig, and VS Code settings.
import { runShellCommand } from "../core/shell.js";
import { EDITORCONFIG, vscodeSettings, vscodeExtensions, ciNodeWorkflow } from "./shared.js";

export const reactGenerator = {
    id: "react",
    label: "React",
    description: "React + TypeScript via Vite, ESLint, GitHub Actions CI",
    tags: ["frontend", "javascript", "js", "typescript", "web", "ui"],
    recommends: ["eslint", "prettier", "vercel"],
    requiresTool: { command: "npm", hint: "Install Node.js (e.g. `devforgekit component install node`), which ships npm." },

    async scaffold({ name, parentDir }) {
        return runShellCommand(`npm create vite@latest "${name}" -- --template react-ts`, { cwd: parentDir });
    },

    generate({ name }) {
        return [
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".vscode/settings.json", content: vscodeSettings() },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["dbaeumer.vscode-eslint", "esbenp.prettier-vscode"]) },
            { path: ".github/workflows/ci.yml", content: ciNodeWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nA React + TypeScript app generated by \`devforgekit new react\` (Vite).\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`npm run dev\` | Start the Vite dev server |\n| \`npm run build\` | Production build |\n| \`npm run preview\` | Preview the production build locally |\n| \`npm run lint\` | ESLint |\n\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "npm install", "npm run dev"];
    }
};
