// Rust Axum generator (v1.2.2 Tier 2): fully hand-written - a Cargo.toml
// + src/main.rs is all a minimal Axum service needs. `cargo` isn't
// required to generate the files, only to build/run them afterward.
import { commandExists, runShellCommand } from "../core/shell.js";
import { confirm } from "../lib/prompts.js";
import { EDITORCONFIG, vscodeSettings, vscodeExtensions } from "./shared.js";

// promptOptions() - Docker used to be hard-coded on with no way to opt
// out (this generator never called promptOptions at all) - unlike every
// other backend stack, which all expose a real toggle. Defaults to true
// so existing non-interactive callers (and this file's own tests, which
// call generate() with no `options` at all) see unchanged behavior.
async function promptOptions(flags) {
    const docker = flags.docker ?? await confirm("Include a Dockerfile?", true);
    return { docker };
}

function cargoToml(name) {
    return `[package]
name = "${name.replace(/-/g, "_")}"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower-http = { version = "0.6", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
`;
}

function mainRs() {
    return `use axum::{routing::get, Json, Router};
use serde_json::{json, Value};

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    let app = Router::new().route("/health", get(health));

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    tracing::info!("listening on {}", listener.local_addr().unwrap());
    axum::serve(listener, app).await.unwrap();
}

async fn health() -> Json<Value> {
    Json(json!({ "status": "ok" }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::Body;
    use axum::http::Request;
    use tower::ServiceExt;

    #[tokio::test]
    async fn health_returns_ok() {
        let app = Router::new().route("/health", get(health));
        let response = app
            .oneshot(Request::builder().uri("/health").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(response.status(), 200);
    }
}
`;
}

function dockerfile(name) {
    const crateName = name.replace(/-/g, "_");
    return `FROM rust:1.82-alpine AS builder
RUN apk add --no-cache musl-dev
WORKDIR /app
COPY . .
RUN cargo build --release

FROM alpine:3.20
COPY --from=builder /app/target/release/${crateName} /${crateName}
EXPOSE 3000
CMD ["/${crateName}"]
`;
}

function ciWorkflow() {
    return `name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo build
      - run: cargo test
`;
}

export const rustAxumGenerator = {
    id: "rust-axum",
    label: "Rust Axum",
    description: "Rust + Axum web framework, tests, Docker, CI",
    tags: ["backend", "rust", "api", "web"],
    recommends: ["rust", "cargo", "docker"],
    requiresTool: null,
    promptOptions,

    generate({ name, options = {} }) {
        const docker = options.docker !== false;
        const files = [
            { path: "Cargo.toml", content: cargoToml(name) },
            { path: "src/main.rs", content: mainRs() },
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".env.example", content: "PORT=3000\n" },
            { path: ".gitignore", content: "/target\nCargo.lock\n.env\n.DS_Store\n" },
            { path: ".vscode/settings.json", content: vscodeSettings({ "rust-analyzer.check.command": "clippy" }) },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["rust-lang.rust-analyzer", "tamasfe.even-better-toml"]) },
            { path: ".github/workflows/ci.yml", content: ciWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nA Rust Axum API generated by \`devforgekit new rust-axum\`.\n\n## Getting started\n\n\`\`\`bash\ncp .env.example .env\ncargo run\n\`\`\`\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`cargo run\` | Run the server |\n| \`cargo test\` | Run tests |\n| \`cargo clippy\` | Lint |\n| \`cargo fmt\` | Format |\n${docker ? `| \`docker build -t ${name} .\` | Build a production image |\n` : ""}\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];
        if (docker) {
            files.push(
                { path: "Dockerfile", content: dockerfile(name) },
                { path: ".dockerignore", content: "target\n.git\n" }
            );
        }
        return files;
    },

    async postGenerate({ dir }) {
        if (await commandExists("cargo")) {
            await runShellCommand("cargo fetch", { cwd: dir, silent: true });
        }
    },

    nextSteps({ name }) {
        return [`cd ${name}`, "cargo run"];
    }
};
