// SvelteKit generator (v2.0.9): scaffolds with the official `sv create`
// CLI (the successor to the deprecated `create-svelte`/`npm create
// svelte@latest` flow - see https://svelte.dev/blog/sv-the-svelte-cli),
// non-interactively via `--template minimal --types ts --no-add-ons
// --no-install`, then layers ESLint/Prettier config, Docker, GitHub
// Actions, and an .env.example by hand - the same division of labor
// nextjs.js uses for create-next-app.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { runShellCommand } from "../core/shell.js";
import { confirm } from "../lib/prompts.js";
import { EDITORCONFIG, vscodeSettings, vscodeExtensions, ciNodeWorkflow, dockerignoreNode } from "./shared.js";

async function promptOptions(flags) {
    const tailwind = flags.tailwind ?? await confirm("Add Tailwind CSS?", true);
    const docker = flags.docker ?? await confirm("Include a production Dockerfile?", true);
    return { tailwind, docker };
}

function prettierrc() {
    return `${JSON.stringify({ semi: true, singleQuote: false, trailingComma: "es5", tabWidth: 2, plugins: ["prettier-plugin-svelte"] }, null, 2)}\n`;
}

// eslintConfig() - `sv create --no-add-ons` deliberately skips ESLint
// entirely (no config file at all), but postGenerate() below still adds
// eslint/eslint-plugin-svelte as devDependencies and a `lint` script -
// without this file `npm run lint` failed outright on every generated
// project (a real bug, found auditing this generator for v2.1.2).
function eslintConfig() {
    return `import js from "@eslint/js";
import svelte from "eslint-plugin-svelte";

export default [
    js.configs.recommended,
    ...svelte.configs["flat/recommended"],
    {
        ignores: ["build/", ".svelte-kit/", "dist/", "node_modules/"]
    }
];
`;
}

function dockerfile() {
    // `npm install`, not `npm ci`: scaffold() below passes --no-install so
    // no package-lock.json exists right after generation - `npm ci` would
    // fail on a fresh project's first `docker build` (same reasoning
    // nextjs.js's Dockerfile comment gives).
    return `FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/build ./build
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev
EXPOSE 3000
CMD ["node", "build"]
`;
}

export const sveltekitGenerator = {
    id: "sveltekit",
    label: "SvelteKit",
    description: "TypeScript, ESLint, Prettier, optional Tailwind CSS, Docker, GitHub Actions",
    tags: ["frontend", "javascript", "js", "typescript", "web"],
    recommends: ["vercel", "eslint", "prettier"],
    requiresTool: { command: "npx", hint: "Install Node.js (e.g. `devforgekit component install node`), which ships npx." },
    promptOptions,
    skipGitInit: false,

    async scaffold({ name, parentDir, options }) {
        void options;
        return runShellCommand(
            `npx --yes sv create "${name}" --template minimal --types ts --no-add-ons --no-install`,
            { cwd: parentDir }
        );
    },

    generate({ name, options }) {
        const files = [
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".env.example", content: "# Copy to .env\nPUBLIC_APP_URL=http://localhost:5173\n" },
            { path: ".vscode/settings.json", content: vscodeSettings({ "editor.defaultFormatter": "esbenp.prettier-vscode" }) },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["svelte.svelte-vscode", "esbenp.prettier-vscode", "dbaeumer.vscode-eslint"]) },
            { path: ".github/workflows/ci.yml", content: ciNodeWorkflow() },
            { path: ".prettierrc.json", content: prettierrc() },
            { path: "eslint.config.js", content: eslintConfig() }
        ];

        if (options.docker) {
            files.push(
                { path: "Dockerfile", content: dockerfile() },
                { path: ".dockerignore", content: dockerignoreNode() }
            );
        }

        files.push({
            path: "README.md",
            content: `# ${name}\n\nA SvelteKit app generated by \`devforgekit new sveltekit\` - TypeScript, ESLint, Prettier${options.tailwind ? ", Tailwind CSS" : ""}${options.docker ? ", Docker" : ""}.\n\n## Getting started\n\n\`\`\`bash\nnpm install\ncp .env.example .env\nnpm run dev\n\`\`\`\n\nOpen [http://localhost:5173](http://localhost:5173).\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`npm run dev\` | Start the dev server |\n| \`npm run build\` | Production build |\n| \`npm run preview\` | Preview the production build |\n| \`npm run check\` | Type-check with svelte-check |\n\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
        });

        return files;
    },

    postGenerate({ dir, options }) {
        // package.json exists (from `sv create`); add ESLint/Prettier and,
        // if requested, Tailwind, so `npm install` pulls everything in one
        // pass instead of the user hand-editing package.json themselves -
        // same pattern nextjs.js's postGenerate uses.
        const pkgPath = path.join(dir, "package.json");
        const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
        pkg.devDependencies = pkg.devDependencies || {};

        Object.assign(pkg.devDependencies, {
            eslint: "^9.17.0",
            "eslint-plugin-svelte": "^2.46.1",
            prettier: "^3.4.2",
            "prettier-plugin-svelte": "^3.3.2"
        });
        pkg.scripts = { ...pkg.scripts, lint: "eslint . && prettier --check .", format: "prettier --write ." };

        if (options.tailwind) {
            Object.assign(pkg.devDependencies, { tailwindcss: "^4.0.0", "@tailwindcss/vite": "^4.0.0" });
        }

        writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
    },

    nextSteps({ name, options }) {
        const steps = [`cd ${name}`, "npm install"];
        if (options.tailwind) steps.push("# Tailwind CSS: follow https://tailwindcss.com/docs/installation/framework-guides/sveltekit to wire the Vite plugin into vite.config.ts");
        steps.push("cp .env.example .env", "npm run dev");
        return steps;
    }
};
