// Tauri generator (v1.2.2 Tier 2): scaffolds with the official
// `create-tauri-app` (vanilla TypeScript frontend template), then layers
// a frontend-only CI (a real Tauri build needs the Rust toolchain +
// platform-specific system deps, which isn't assumed to exist in every
// CI runner, so CI here checks the frontend and `cargo check` instead of
// a full `tauri build`).
import { runShellCommand, commandExists } from "../core/shell.js";
import { EDITORCONFIG, vscodeSettings, vscodeExtensions } from "./shared.js";

function ciWorkflow() {
    return `name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install frontend dependencies
        run: npm ci

      - name: Lint/build frontend
        run: npm run build --if-present

      - uses: dtolnay/rust-toolchain@stable

      - name: cargo check (src-tauri)
        run: cargo check --manifest-path src-tauri/Cargo.toml
`;
}

export const tauriGenerator = {
    id: "tauri",
    label: "Tauri",
    description: "Desktop app: Rust core + TypeScript frontend, via the official create-tauri-app CLI",
    tags: ["desktop", "rust", "typescript", "javascript", "js"],
    recommends: ["tauri-cli", "rust", "cargo"],
    requiresTool: { command: "npx", hint: "Install Node.js (e.g. `devforgekit component install node`), which ships npx. A Rust toolchain (`cargo`) is also required to build/run - see https://tauri.app/start/prerequisites/." },

    async scaffold({ name, parentDir }) {
        return runShellCommand(
            `npx --yes create-tauri-app@latest "${name}" --template vanilla-ts --manager npm --yes`,
            { cwd: parentDir }
        );
    },

    generate({ name }) {
        return [
            { path: ".editorconfig", content: EDITORCONFIG },
            { path: ".vscode/settings.json", content: vscodeSettings() },
            { path: ".vscode/extensions.json", content: vscodeExtensions(["tauri-apps.tauri-vscode", "rust-lang.rust-analyzer"]) },
            { path: ".github/workflows/ci.yml", content: ciWorkflow() },
            {
                path: "README.md",
                content: `# ${name}\n\nA Tauri desktop app generated by \`devforgekit new tauri\` (Rust core + TypeScript frontend).\n\n## Prerequisites\n\n- Node.js\n- A Rust toolchain (\`cargo\`) - see https://tauri.app/start/prerequisites/\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm run tauri dev\n\`\`\`\n\n## Scripts\n\n| Command | What it does |\n| --- | --- |\n| \`npm run tauri dev\` | Run the desktop app in dev mode |\n| \`npm run tauri build\` | Build a production installer |\n\n---\n\nGenerated by \`devforgekit new\` (DevForgeKit's Project Generator).\n`
            }
        ];
    },

    async nextSteps({ name }) {
        const hasCargo = await commandExists("cargo");
        return [
            `cd ${name}`,
            "npm install",
            ...(hasCargo ? [] : ["# install a Rust toolchain first: https://tauri.app/start/prerequisites/"]),
            "npm run tauri dev"
        ];
    }
};
